### ISSUE TITLE
Support for alpha-numeric variable names in custom variables

### ISSUE THREAD

**Issue by naveen1941** [handsontable/formula-parser#29] opened 2017-06-18 10:08 UTC
Example: 
    var parser = new formulaParser();
    parser.setVariable('K01', 5);
    parser.setVariable('K02', 2);
    var result = parser.parse('K01 * K02');
Result:  { error: '#VALUE!', result: null }

**Comment by apumapho** [comment] 2017-11-05 22:40
@naveen1941 Ran into this too and was about to submit a pull request with update to the parser.  However, the grammar parser is (and upon reflection, seemingly should) prioritizing "K1" as a RELATIVE_CELL to an excel-like cell.

In `formula-parser/src/grammar-parser/grammar-parser.jison` you'll see that RELATIVE_CELL is defined as `[A-Za-z]+[0-9]+`.

```
[A-Za-z]+[0-9]+                                         {return 'RELATIVE_CELL';}
[A-Za-z\.]+(?=[(])                                      {return 'FUNCTION';}
[A-Za-z]{1,}[A-Za-z_0-9]+                               {return 'VARIABLE';}
[A-Za-z_]+                                              {return 'VARIABLE';}
```

As a valid workaround, you can use an underscore if you really must have a number at the end of a variable name:

```javascript
var parser = new formulaParser();
parser.setVariable('K_01', 5);
parser.setVariable('K_02', 2);
var result = parser.parse('K_01 * K_02');
```

**Comment by ArtemKosogorov** [comment] 2017-12-18 04:56
Having underscore between letters and numbers helps, yet this issue affets all custom variables where numbers follow letters (not only with the numbers at the end).

**Comment by wojciechczerniak** [comment] 2020-01-29 09:19
@AMBudnik It’s explained in the ODFF spec and Excel documentation. Variable can’t look like a cell reference. Letter and number is a cell reference. 

As @apumapho already noticed, it’s by design

**Comment by AMBudnik** [comment] 2020-01-29 09:28
Thanks for noticing @wojciechczerniak 
We can close this topic.

**Closed by AMBudnik** 2020-01-29 09:28 UTC
Labels: Feature
